version: "3.9"

services:
  php:
    build: php
    container_name: test_console_php
    volumes:
      - "../..:/app:delegated"
      - "./php/php.override.ini:/usr/local/etc/php/conf.d/php.override.ini"
    environment:
      # https://blog.jetbrains.com/phpstorm/2012/03/new-in-4-0-easier-debugging-of-remote-php-command-line-scripts/
      PHP_IDE_CONFIG: "serverName=test-console.docker"
  nginx:
    image: nginx:1.21
    container_name: test_console_nginx
    environment:
      VIRTUAL_HOST: test-console.docker
    links:
      - php
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "../..:/app:delegated"
    expose:
      - 80

networks:
  default:
    external: true
    name: nginx-dev-proxy
